language: python
python:
- '3.6.4'
services:
- redis-server
addons:
  postgresql: '9.6'
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install --upgrade pip
- pip install -r pip-freeze.txt --upgrade
- pip install coveralls
- pip install flake8
- npm install -g less
- npm install -g coffee-script
before_script:
- psql -U postgres -c "CREATE USER ureport WITH PASSWORD 'nyaruka';"
- psql -U postgres -c "ALTER ROLE ureport WITH SUPERUSER;"
- psql -U ureport postgres -c "CREATE DATABASE ureport;"
- ln -s $TRAVIS_BUILD_DIR/ureport/settings.py.postgres $TRAVIS_BUILD_DIR/ureport/settings.py
script:
- flake8
- coverage run --source="." manage.py test ureport ureport/admins ureport/assets ureport/contacts ureport/countries ureport/jobs ureport/locations ureport/news ureport/polls ureport/public ureport/utils --verbosity=2 --noinput
after_success:
- coveralls